// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Votify.Persistence.Context;

#nullable disable

namespace Votify.Persistence.Migrations
{
    [DbContext(typeof(VotifyContext))]
    [Migration("20260430201339_AgregarOpcionEmpatePremio")]
    partial class AgregarOpcionEmpatePremio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoriaProyecto", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("integer");

                    b.Property<int>("ProyectosId")
                        .HasColumnType("integer");

                    b.HasKey("CategoriasId", "ProyectosId");

                    b.HasIndex("ProyectosId");

                    b.ToTable("ProyectosCategorias", (string)null);
                });

            modelBuilder.Entity("EventoJuez", b =>
                {
                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<int>("JuradoId")
                        .HasColumnType("integer");

                    b.HasKey("EventoId", "JuradoId");

                    b.HasIndex("JuradoId");

                    b.ToTable("EventosJurado", (string)null);
                });

            modelBuilder.Entity("EventoParticipante", b =>
                {
                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantesId")
                        .HasColumnType("integer");

                    b.HasKey("EventoId", "ParticipantesId");

                    b.HasIndex("ParticipantesId");

                    b.ToTable("EventosParticipantes", (string)null);
                });

            modelBuilder.Entity("EventoVotante", b =>
                {
                    b.Property<int>("EventosId")
                        .HasColumnType("integer");

                    b.Property<int>("VotantesId")
                        .HasColumnType("integer");

                    b.HasKey("EventosId", "VotantesId");

                    b.HasIndex("VotantesId");

                    b.ToTable("EventosVotantes", (string)null);
                });

            modelBuilder.Entity("Votify.Core.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("Votify.Core.Models.Criterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("MulticriterioId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MulticriterioId");

                    b.ToTable("Criterios", (string)null);
                });

            modelBuilder.Entity("Votify.Core.Models.DetalleVoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CriterioId")
                        .HasColumnType("integer");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("integer");

                    b.Property<int>("VotoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriterioId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("VotoId");

                    b.ToTable("DetallesVoto", (string)null);
                });

            modelBuilder.Entity("Votify.Core.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminador")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Borrador");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OrganizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizadorId");

                    b.ToTable("Eventos", (string)null);

                    b.HasDiscriminator<string>("Discriminador").HasValue("Evento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Core.Models.Miembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("QuiereRecibirNotificaciones")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoDeMiembro")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Miembros", (string)null);

                    b.HasDiscriminator<string>("TipoDeMiembro").HasValue("Miembro");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Core.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MiembroId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlAccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId");

                    b.ToTable("Notificacion");
                });

            modelBuilder.Entity("Votify.Core.Models.Premio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PermiteEmpate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Premios", (string)null);
                });

            modelBuilder.Entity("Votify.Core.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CriterioA")
                        .HasColumnType("double precision");

                    b.Property<double>("CriterioB")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoProyecto")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("Proyectos", (string)null);

                    b.HasDiscriminator<string>("TipoProyecto").HasValue("Proyecto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Core.Models.Votacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EnviarNotificacionApertura")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaCerrada")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Cerrada");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("NotificacionAperturaEnviada")
                        .HasColumnType("boolean");

                    b.Property<bool>("ResultadosPublicados")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoVotacion")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .IsUnique();

                    b.ToTable("Votaciones", (string)null);

                    b.HasDiscriminator<string>("TipoVotacion").HasValue("Votacion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Core.Models.Votante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anonimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Votantes", (string)null);
                });

            modelBuilder.Entity("Votify.Core.Models.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anonimo")
                        .HasColumnType("boolean");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HashAnonimo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer");

                    b.Property<double>("PuntuacionBase")
                        .HasColumnType("double precision");

                    b.Property<string>("TipoVoto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("VotacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("VotacionId");

                    b.ToTable("Votos", (string)null);

                    b.HasDiscriminator<string>("TipoVoto").HasValue("Voto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Core.Models.ESportsEvent", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Evento");

                    b.HasDiscriminator().HasValue("ESport");
                });

            modelBuilder.Entity("Votify.Core.Models.HackathonEvent", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Evento");

                    b.HasDiscriminator().HasValue("Hackathon");
                });

            modelBuilder.Entity("Votify.Core.Models.InnovationFairEvent", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Evento");

                    b.HasDiscriminator().HasValue("FeriaInnovacion");
                });

            modelBuilder.Entity("Votify.Core.Models.Juez", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Miembro");

                    b.Property<int?>("VotacionId")
                        .HasColumnType("integer");

                    b.HasIndex("VotacionId");

                    b.HasDiscriminator().HasValue("Juez");
                });

            modelBuilder.Entity("Votify.Core.Models.Organizador", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Miembro");

                    b.HasDiscriminator().HasValue("Organizador");
                });

            modelBuilder.Entity("Votify.Core.Models.Participante", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Miembro");

                    b.Property<string>("ColorFondo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("InstitucionEducativa")
                        .HasColumnType("text");

                    b.Property<string>("Intereses")
                        .HasColumnType("text");

                    b.Property<string>("UrlFoto")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Participante");
                });

            modelBuilder.Entity("Votify.Core.Models.AiProject", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Proyecto");

                    b.HasDiscriminator().HasValue("AI");
                });

            modelBuilder.Entity("Votify.Core.Models.CybersecurityProject", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Proyecto");

                    b.HasDiscriminator().HasValue("Ciberseguridad");
                });

            modelBuilder.Entity("Votify.Core.Models.SustainabilityProject", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Proyecto");

                    b.HasDiscriminator().HasValue("Sostenibilidad");
                });

            modelBuilder.Entity("Votify.Core.Models.Multicriterio", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Votacion");

                    b.Property<bool>("UsaPesos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasDiscriminator().HasValue("Multicriterio");
                });

            modelBuilder.Entity("Votify.Core.Models.Popular", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Votacion");

                    b.Property<int>("MaxSelection")
                        .HasColumnType("integer");

                    b.Property<bool>("PermiteAutoVoto")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Popular");
                });

            modelBuilder.Entity("Votify.Core.Models.Puntuacion", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Votacion");

                    b.Property<int>("ValorMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.HasDiscriminator().HasValue("Puntuacion");
                });

            modelBuilder.Entity("Votify.Core.Models.VotoExperto", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Voto");

                    b.Property<int?>("JuezId")
                        .HasColumnType("integer");

                    b.HasIndex("JuezId");

                    b.HasDiscriminator().HasValue("Experto");
                });

            modelBuilder.Entity("Votify.Core.Models.VotoPublico", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Voto");

                    b.Property<int?>("VotanteId")
                        .HasColumnType("integer");

                    b.HasIndex("VotanteId");

                    b.HasDiscriminator().HasValue("Publico");
                });

            modelBuilder.Entity("Votify.Core.Models.VotoSponsor", b =>
                {
                    b.HasBaseType("Votify.Core.Models.Voto");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Sponsor");
                });

            modelBuilder.Entity("CategoriaProyecto", b =>
                {
                    b.HasOne("Votify.Core.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votify.Core.Models.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventoJuez", b =>
                {
                    b.HasOne("Votify.Core.Models.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votify.Core.Models.Juez", null)
                        .WithMany()
                        .HasForeignKey("JuradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventoParticipante", b =>
                {
                    b.HasOne("Votify.Core.Models.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votify.Core.Models.Participante", null)
                        .WithMany()
                        .HasForeignKey("ParticipantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventoVotante", b =>
                {
                    b.HasOne("Votify.Core.Models.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votify.Core.Models.Votante", null)
                        .WithMany()
                        .HasForeignKey("VotantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Votify.Core.Models.Categoria", b =>
                {
                    b.HasOne("Votify.Core.Models.Evento", "Evento")
                        .WithMany("CategoriasEvento")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Votify.Core.Models.Criterio", b =>
                {
                    b.HasOne("Votify.Core.Models.Multicriterio", "Multicriterio")
                        .WithMany("Criterios")
                        .HasForeignKey("MulticriterioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Multicriterio");
                });

            modelBuilder.Entity("Votify.Core.Models.DetalleVoto", b =>
                {
                    b.HasOne("Votify.Core.Models.Criterio", "Criterio")
                        .WithMany()
                        .HasForeignKey("CriterioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Votify.Core.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Votify.Core.Models.Voto", "Voto")
                        .WithMany("Detalles")
                        .HasForeignKey("VotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterio");

                    b.Navigation("Proyecto");

                    b.Navigation("Voto");
                });

            modelBuilder.Entity("Votify.Core.Models.Evento", b =>
                {
                    b.HasOne("Votify.Core.Models.Organizador", "Organizador")
                        .WithMany()
                        .HasForeignKey("OrganizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("Votify.Core.Models.Notificacion", b =>
                {
                    b.HasOne("Votify.Core.Models.Miembro", "Miembro")
                        .WithMany("Notificaciones")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("Votify.Core.Models.Premio", b =>
                {
                    b.HasOne("Votify.Core.Models.Categoria", "Categoria")
                        .WithMany("Premios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Votify.Core.Models.Proyecto", b =>
                {
                    b.HasOne("Votify.Core.Models.Participante", "Participante")
                        .WithMany("Proyectos")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Votify.Core.Models.Votacion", b =>
                {
                    b.HasOne("Votify.Core.Models.Categoria", "Categoria")
                        .WithOne("Votacion")
                        .HasForeignKey("Votify.Core.Models.Votacion", "CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Votify.Core.Models.Voto", b =>
                {
                    b.HasOne("Votify.Core.Models.Proyecto", "Proyecto")
                        .WithMany("Votos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votify.Core.Models.Votacion", "Votacion")
                        .WithMany("Votos")
                        .HasForeignKey("VotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Votacion");
                });

            modelBuilder.Entity("Votify.Core.Models.Juez", b =>
                {
                    b.HasOne("Votify.Core.Models.Votacion", null)
                        .WithMany("JuecesAutorizados")
                        .HasForeignKey("VotacionId");
                });

            modelBuilder.Entity("Votify.Core.Models.VotoExperto", b =>
                {
                    b.HasOne("Votify.Core.Models.Juez", "Juez")
                        .WithMany()
                        .HasForeignKey("JuezId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Juez");
                });

            modelBuilder.Entity("Votify.Core.Models.VotoPublico", b =>
                {
                    b.HasOne("Votify.Core.Models.Votante", "Votante")
                        .WithMany("Votos")
                        .HasForeignKey("VotanteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("Votify.Core.Models.Categoria", b =>
                {
                    b.Navigation("Premios");

                    b.Navigation("Votacion");
                });

            modelBuilder.Entity("Votify.Core.Models.Evento", b =>
                {
                    b.Navigation("CategoriasEvento");
                });

            modelBuilder.Entity("Votify.Core.Models.Miembro", b =>
                {
                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("Votify.Core.Models.Proyecto", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Votify.Core.Models.Votacion", b =>
                {
                    b.Navigation("JuecesAutorizados");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Votify.Core.Models.Votante", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Votify.Core.Models.Voto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Votify.Core.Models.Participante", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("Votify.Core.Models.Multicriterio", b =>
                {
                    b.Navigation("Criterios");
                });
#pragma warning restore 612, 618
        }
    }
}
