// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Votify.Persistence.Context;

#nullable disable

namespace Votify.Persistence.Migrations
{
    [DbContext(typeof(VotifyContext))]
    partial class VotifyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoriaEntityProyectoEntity", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("integer");

                    b.Property<int>("ProyectosId")
                        .HasColumnType("integer");

                    b.HasKey("CategoriasId", "ProyectosId");

                    b.HasIndex("ProyectosId");

                    b.ToTable("CategoriaEntityProyectoEntity");
                });

            modelBuilder.Entity("EventoEntityMiembroEntity", b =>
                {
                    b.Property<int>("EventosId")
                        .HasColumnType("integer");

                    b.Property<int>("MiembrosId")
                        .HasColumnType("integer");

                    b.HasKey("EventosId", "MiembrosId");

                    b.HasIndex("MiembrosId");

                    b.ToTable("EventoEntityMiembroEntity");
                });

            modelBuilder.Entity("EventoEntityVotanteEntity", b =>
                {
                    b.Property<int>("EventosId")
                        .HasColumnType("integer");

                    b.Property<int>("VotantesId")
                        .HasColumnType("integer");

                    b.HasKey("EventosId", "VotantesId");

                    b.HasIndex("VotantesId");

                    b.ToTable("EventoEntityVotanteEntity");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.CategoriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.CriterioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("MulticriterioId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<int>("VotacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VotacionId");

                    b.ToTable("Criterios");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.EventoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizadorId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.MiembroEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoMiembro")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Miembros");

                    b.HasDiscriminator<string>("TipoMiembro").HasValue("MiembroEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Persistence.Entities.PremioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.ProyectoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId")
                        .IsUnique();

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.VotacionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoVotacion")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .IsUnique();

                    b.ToTable("Votaciones");

                    b.HasDiscriminator<string>("TipoVotacion").HasValue("VotacionEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Persistence.Entities.VotanteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anonimo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Votantes");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.VotoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anonimo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashAnonimo")
                        .HasColumnType("text");

                    b.Property<int?>("JuezId")
                        .HasColumnType("integer");

                    b.Property<int>("VotacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("VotanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JuezId");

                    b.HasIndex("VotacionId");

                    b.HasIndex("VotanteId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.JuezEntity", b =>
                {
                    b.HasBaseType("Votify.Persistence.Entities.MiembroEntity");

                    b.HasDiscriminator().HasValue("Juez");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.OrganizadorEntity", b =>
                {
                    b.HasBaseType("Votify.Persistence.Entities.MiembroEntity");

                    b.HasDiscriminator().HasValue("Organizador");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.ParticipanteEntity", b =>
                {
                    b.HasBaseType("Votify.Persistence.Entities.MiembroEntity");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Participante");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.MulticriterioEntity", b =>
                {
                    b.HasBaseType("Votify.Persistence.Entities.VotacionEntity");

                    b.Property<bool>("UsaPesos")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Multicriterio");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.PopularEntity", b =>
                {
                    b.HasBaseType("Votify.Persistence.Entities.VotacionEntity");

                    b.Property<int>("MaxSelection")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Popular");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.PuntuacionEntity", b =>
                {
                    b.HasBaseType("Votify.Persistence.Entities.VotacionEntity");

                    b.Property<int>("ValorMax")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Puntuacion");
                });

            modelBuilder.Entity("CategoriaEntityProyectoEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.CategoriaEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votify.Persistence.Entities.ProyectoEntity", null)
                        .WithMany()
                        .HasForeignKey("ProyectosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventoEntityMiembroEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.EventoEntity", null)
                        .WithMany()
                        .HasForeignKey("EventosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votify.Persistence.Entities.MiembroEntity", null)
                        .WithMany()
                        .HasForeignKey("MiembrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventoEntityVotanteEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.EventoEntity", null)
                        .WithMany()
                        .HasForeignKey("EventosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votify.Persistence.Entities.VotanteEntity", null)
                        .WithMany()
                        .HasForeignKey("VotantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Votify.Persistence.Entities.CategoriaEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.EventoEntity", "Evento")
                        .WithMany("CategoriasEvento")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.CriterioEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.MulticriterioEntity", "Votacion")
                        .WithMany("Criterios")
                        .HasForeignKey("VotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Votacion");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.EventoEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.OrganizadorEntity", "Organizador")
                        .WithMany()
                        .HasForeignKey("OrganizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.PremioEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.CategoriaEntity", "Categoria")
                        .WithMany("Premios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.ProyectoEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.ParticipanteEntity", "Participante")
                        .WithOne("Proyecto")
                        .HasForeignKey("Votify.Persistence.Entities.ProyectoEntity", "ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.VotacionEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.CategoriaEntity", "Categoria")
                        .WithOne("Votacion")
                        .HasForeignKey("Votify.Persistence.Entities.VotacionEntity", "CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.VotoEntity", b =>
                {
                    b.HasOne("Votify.Persistence.Entities.JuezEntity", "Juez")
                        .WithMany()
                        .HasForeignKey("JuezId");

                    b.HasOne("Votify.Persistence.Entities.VotacionEntity", "Votacion")
                        .WithMany("Votos")
                        .HasForeignKey("VotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Votify.Persistence.Entities.VotanteEntity", "Votante")
                        .WithMany("Votos")
                        .HasForeignKey("VotanteId");

                    b.Navigation("Juez");

                    b.Navigation("Votacion");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.CategoriaEntity", b =>
                {
                    b.Navigation("Premios");

                    b.Navigation("Votacion");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.EventoEntity", b =>
                {
                    b.Navigation("CategoriasEvento");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.VotacionEntity", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.VotanteEntity", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.ParticipanteEntity", b =>
                {
                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Votify.Persistence.Entities.MulticriterioEntity", b =>
                {
                    b.Navigation("Criterios");
                });
#pragma warning restore 612, 618
        }
    }
}
